### ISSUE TITLE
using IUS repo causes depsolving problems for python27-libs

### ISSUE THREAD

**Issue by ArcAIN6** [iuscommunity-pkg/python27#4]
Unsure if this project is official IUS, but when attempting to install python27 into centos 5.x using IUS repo, there is a dependecy issue. 

Resolving Dependencies
--> Running transaction check
---> Package python27.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: python27-libs = 2.7.9-3.ius.el5 for package: python27
--> Processing Dependency: libpython2.7.so.1.0 for package: python27
---> Package python27-devel.i386 0:2.7.9-3.ius.el5 set to be updated
---> Package python27-setuptools.noarch 0:15.2-1.ius.el5 set to be updated
---> Package python27-virtualenv.noarch 0:12.1.1-1.ius.el5 set to be updated
--> Running transaction check
---> Package python27-libs.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: libffi.so.5 for package: python27-libs
--> Finished Dependency Resolution
python27-libs-2.7.9-3.ius.el5.i386 from ius has depsolving problems
  --> Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
Error: Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)

**Comment by carlgeorge** [comment]
Installing python27 on CentOS 5.11 64bit works fine for me.  Before we go further with troubleshooting, let's check on a few things.

* Your output indicates that you are trying to use i386 packages.  Please ensure you are on a i386 system, not a x86_64 system.
* You mentioned CentOS 5, but the output shows packages with "el5" tags.  Those are built against RHEL5, not CentOS5.  While 99% of the times this doesn't make a difference, sometimes it presents issues.  Please switch to using our CentOS packages, which will have a tag of "centos5".
* You mentioned CentOS 5.x.  What exact version of CentOS are you using?  Our public repos contain packages built against the latest base release, which is currently 5.11.  Library issues such as this are common when using an outdated base system.  Please ensure your system is fully updated.

**Comment by ArcAIN6** [comment]
Set up a clean server to test on, this is the procedure i followed, please advise if i've missed something important.

[xXxXxXx@test11 ~]# cat /etc/redhat-release 
CentOS release 5.11 (Final)
[xXxXxXx@test11 ~]# wget https://dl.iuscommunity.org/pub/ius/stable/CentOS/5/x86_64/ius-release-1.0-14.ius.centos5.noarch.rpm
[xXxXxXx@test11 ~]#  rpm -Uvh ius-release-1.0-14.ius.centos5.noarch.rpm
[xXxXxXx@test11 ~]#  yum install python27 python27-devel python27-setuptools python27-virtualenv
Loaded plugins: fastestmirror, priorities, protectbase, replace
Loading mirror speeds from cached hostfile
 * addons: mirror.tzulo.com
 * base: mirror.vcu.edu
 * extras: bay.uchicago.edu
 * ius: ord.mirror.rackspace.com
 * updates: mirror.metrocast.net
0 packages excluded due to repository protections
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package python27.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: python27-libs = 2.7.9-3.ius.el5 for package: python27
--> Processing Dependency: libpython2.7.so.1.0 for package: python27
---> Package python27-devel.i386 0:2.7.9-3.ius.el5 set to be updated
---> Package python27-setuptools.noarch 0:15.2-1.ius.el5 set to be updated
---> Package python27-virtualenv.noarch 0:12.1.1-1.ius.el5 set to be updated
--> Running transaction check
---> Package python27-libs.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: libffi.so.5 for package: python27-libs
--> Finished Dependency Resolution
python27-libs-2.7.9-3.ius.el5.i386 from ius has depsolving problems
  --> Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
Error: Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
Error: Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
 You could try using --skip-broken to work around the problem
 You could try running: package-cleanup --problems
                        package-cleanup --dupes
                        rpm -Va --nofiles --nodigest
[xXxXxXx@test11 ~]#

**Comment by ArcAIN6** [comment]
the system is 32bit, CentOS 5.11 (final)

installed https://dl.iuscommunity.org/pub/ius/stable/CentOS/5/i386/ius-release-1.0-14.ius.centos5.noarch.rpm

then attempted to install packages:

[xXxXxXx@test11 ~]# yum install python27 python27-devel python27-setuptools python27-virtualenv
Loaded plugins: fastestmirror, priorities, protectbase, replace
Loading mirror speeds from cached hostfile
 * addons: mirror.tzulo.com
 * base: mirror.atlanticmetro.net
 * extras: mirror.cisp.com
 * ius: mirror.symnds.com
 * updates: mirror.us.leaseweb.net
ius                                                                                                                                   | 2.2 kB     00:00     
Not using downloaded repomd.xml because it is older than what we have:
  Current   : Tue Jun  2 03:36:57 2015
  Downloaded: Tue Jun  2 03:34:37 2015
0 packages excluded due to repository protections
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package python27.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: python27-libs = 2.7.9-3.ius.el5 for package: python27
--> Processing Dependency: libpython2.7.so.1.0 for package: python27
---> Package python27-devel.i386 0:2.7.9-3.ius.el5 set to be updated
---> Package python27-setuptools.noarch 0:15.2-1.ius.el5 set to be updated
---> Package python27-virtualenv.noarch 0:12.1.1-1.ius.el5 set to be updated
--> Running transaction check
---> Package python27-libs.i386 0:2.7.9-3.ius.el5 set to be updated
--> Processing Dependency: libffi.so.5 for package: python27-libs
--> Finished Dependency Resolution
python27-libs-2.7.9-3.ius.el5.i386 from ius has depsolving problems
  --> Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
Error: Missing Dependency: libffi.so.5 is needed by package python27-libs-2.7.9-3.ius.el5.i386 (ius)
 You could try using --skip-broken to work around the problem
 You could try running: package-cleanup --problems
                        package-cleanup --dupes
                        rpm -Va --nofiles --nodigest
[xXxXxXx@test11 ~]# 

If 64bit version works for you, then there appears that libffi is being supplied either by the 64bit repository, or another repository you have enabled. As for me, i can't seem to find a resolution. 

While epel does indeed have libffi, it appears the repo isn't allowing installation for some reason, or it isn't being reported within the repo search. 

Manually installing libffi from http://mirror.pnl.gov/epel//5/i386/libffi-3.0.5-1.el5.i386.rpm does allow yum to continue, but alas, still no joy as now i'm recieving 404 errors for every mirror:

Error Downloading Packages:
  python27-2.7.9-3.ius.el5.i386: failure: python27-2.7.9-3.ius.el5.i386.rpm from ius: [Errno 256] No more mirrors to try.
  python27-setuptools-15.2-1.ius.el5.noarch: failure: python27-setuptools-15.2-1.ius.el5.noarch.rpm from ius: [Errno 256] No more mirrors to try.
  python27-libs-2.7.9-3.ius.el5.i386: failure: python27-libs-2.7.9-3.ius.el5.i386.rpm from ius: [Errno 256] No more mirrors to try.
  python27-devel-2.7.9-3.ius.el5.i386: failure: python27-devel-2.7.9-3.ius.el5.i386.rpm from ius: [Errno 256] No more mirrors to try.
  python27-virtualenv-12.1.1-1.ius.el5.noarch: failure: python27-virtualenv-12.1.1-1.ius.el5.noarch.rpm from ius: [Errno 256] No more mirrors to try.

So i guess i'll manually download those as well. 

Shame really, if i had the option, i would have upgraded to CentOS 7 ages ago. (yay work politics!)

**Comment by ArcAIN6** [comment]
can confirm manual download and install works fine. not sure why the repo's aren't finding, or 404'ing on packages.

**Comment by carlgeorge** [comment]
You are correct, libffi is provided by EPEL on EL5.  There are many IUS packages that have requirements from EPEL.  Because of this, ius-release requires epel-release.  You couldn't have installed ius-release having epel-release already installed.  I'm guessing that you have epel-release installed but disabled.  Make sure that `enabled=1` is in the `[epel]` stanza in `/etc/yum.repos.d/epel.repo`.

It's not clear why you are getting 404 errors from an IUS mirror.  The mirror you are pointing at (mirror.symnds.com) is up to date, and I can download packages directly.  Try these things to troubleshoot.

* Try to manually download `http://mirror.symnds.com/distributions/ius/stable/CentOS/5/i386/python27-2.7.9-3.ius.centos5.i386.rpm` from the system having issues to rule out network issues between you and that mirror.
* Clear your yum cache (`yum clean all`) and try again.

**Comment by carlgeorge** [comment]
Since we've haven't heard back, I'll assume you got the issue sorted out.  Let us know if you have further problems.
