### ISSUE TITLE
gdb returns "frame information optimized out"

### ISSUE THREAD

**Issue by radar-aol-pl** [iuscommunity-pkg/python27#5]
When I try to run:
gdb python2.7 19199 --batch --eval-command="thread apply all py-bt"
it doesn't show full stacktrace. For example:

[...]
[New LWP 19226]
[New LWP 19225]
[New LWP 19224]
[New LWP 19223]
[New LWP 19222]
[New LWP 19221]
[New LWP 19220]
[New LWP 19219]
[Thread debugging using libthread_db enabled]
0x00007eff30bc53b3 in select () from /lib64/libc.so.6

Thread 68 (Thread 0x7eff28c85700 (LWP 19219)):
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  (frame information optimized out)

Thread 67 (Thread 0x7eff223bb700 (LWP 19220)):
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  (frame information optimized out)

Thread 66 (Thread 0x7eff219ba700 (LWP 19221)):
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  (frame information optimized out)

Thread 65 (Thread 0x7eff20fb9700 (LWP 19222)):
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  (frame information optimized out)

Thread 64 (Thread 0x7eff13fff700 (LWP 19223)):
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  (frame information optimized out)

There should be more info instead of "frame information optimized out".
Would you help and let me know what should be changed in the package to get full trace when using gdb?

**Comment by radar-aol-pl** [comment]
Additional info:

Dist: CentOS release 6.7 (Final)

Kernel: 2.6.32-573.12.1.el6.x86_64

Python packages:
python-debuginfo-2.6.6-64.el6.x86_64
python27-libs-2.7.11-1.ius.el6.x86_64
python27-test-2.7.11-1.ius.el6.x86_64
python27-debug-2.7.11-1.ius.el6.x86_64
python-2.6.6-64.el6.x86_64
python-pycurl-7.19.0-8.el6.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python27-2.7.11-1.ius.el6.x86_64
python27-tools-2.7.11-1.ius.el6.x86_64
python27-devel-2.7.11-1.ius.el6.x86_64
python27-debuginfo-2.7.11-1.ius.el6.x86_64
python-libs-2.6.6-64.el6.x86_64
python-urlgrabber-3.9.1-9.el6.noarch
rpm-python-4.8.0-47.el6.x86_64
newt-python-0.52.11-3.el6.x86_64

**Comment by b-harper** [comment]
Hey @radar-aol-pl,

Thanks for taking the time to submit this GitHub issue.  With an issue like this, we need to determine if this a bug with the upstream project,  an problem with the way we package the software or maybe a limitation of the base packages in EL6.  

Like most IUS packages, python27 packages we stand on the sholders of tdu

**Comment by b-harper** [comment]
Hey @radar-aol-pl,

Thanks for taking the time to contact us regarding this issue.  With issues like this one, we need to determine is this is a bug with the upstream project, a problem with how the software is packages or maybe a limitation of the base EL packages.  

With almost all of our packages, we stand on the shoulders of giants, and base our packages off Fedora's SRPMs.  Our python27 packages are based on Fedora's python 2.7 packages.  You might want to look at the notes for [Patch112](http://pkgs.fedoraproject.org/cgit/rpms/python.git/tree/python.spec#n374).  

Did you have this issue with previous versions of pyton27?  That Patch112 did get updated in 2.7.10-1.  You could try 2.7.9-3 the version right before 2.7.10-1.

-Ben

**Comment by radar-aol-pl** [comment]
Thanks for prompt reply.
I didn't use your packages before. I used 2.7.6 without debuginfo and native CentOS 2.6.6 rpms:

python-devel-2.6.6-64.el6.x86_64
python-2.6.6-64.el6.x86_64
python-debuginfo-2.6.6-64.el6.x86_64
python-libs-2.6.6-64.el6.x86_64

which - when I run gdb - works above reproach:

Thread 33 (Thread 0x7fdc4d8b3700 (LWP 3467)):
#2 <built-in method read of ssl.SSLContext object at remote 0x7fdc38529c90>
#4 file '/usr/lib64/python2.6/ssl.py', in 'read'
#8 file '/usr/lib64/python2.6/ssl.py', in 'recv'
#12 file '/usr/lib64/python2.6/socket.py', in 'readline'
#16 file '/usr/lib64/python2.6/httplib.py', in '_read_status'
#19 file '/usr/lib64/python2.6/httplib.py', in 'begin'
#22 file '/usr/lib64/python2.6/httplib.py', in 'getresponse'
#25 file '/usr/lib64/python2.6/urllib2.py', in 'do_open'
#28 file '/usr/lib64/python2.6/urllib2.py', in 'https_open'
#33 file '/usr/lib64/python2.6/urllib2.py', in '_call_chain'
#37 file '/usr/lib64/python2.6/urllib2.py', in '_open'
#41 file '/usr/lib64/python2.6/urllib2.py', in 'open'
#45 file '/usr/lib64/python2.6/urllib2.py', in 'urlopen'

**Comment by b-harper** [comment]
It would appear that the python 2.7 packages in Fedora 23 are working correctly.

```
# rpm -q fedora-release
fedora-release-23-1.noarch

# rpm -q python python-debug python-debuginfo
python-2.7.11-3.fc23.x86_64
python-debug-2.7.11-3.fc23.x86_64
python-debuginfo-2.7.11-3.fc23.x86_64

# python threads.py

# gdb python 3853 --batch --eval-command="thread apply all py-bt"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fac5c205691 in PyEval_EvalFrameEx (f=f@entry=0x7fac5c59a750, throwflag=throwflag@entry=0) at /usr/src/debug/Python-2.7.11/Python/ceval.c:2856
2856                DISPATCH();

Thread 1 (Thread 0x7fac5c707700 (LWP 3853)):
Traceback (most recent call first):
  File "threads.py", line 22, in <module>
    pass
```
The threads.py is [from this example][0].  Here is that same thing on EL6 with python27 packages:

```
# rpm -q centos-release
centos-release-6-7.el6.centos.12.3.x86_64

# rpm -q python27 python27-debug python27-debuginfo
python27-2.7.11-1.ius.centos6.x86_64
python27-debug-2.7.11-1.ius.centos6.x86_64
python27-debuginfo-2.7.11-1.ius.centos6.x86_64

# gdb python2.7 8335 --batch --eval-command="thread apply all py-bt"
[New LWP 8337]
[Thread debugging using libthread_db enabled]
0x00007fdeab0425ce in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at /usr/src/debug/Python-2.7.11/Python/ceval.c:2856
2856                DISPATCH();

Thread 2 (Thread 0x7fdea3685700 (LWP 8337)):
Traceback (most recent call first):
  (frame information optimized out)

Thread 1 (Thread 0x7fdeab53c700 (LWP 8335)):
Traceback (most recent call first):
  (frame information optimized out)
```

I got the same results using the older 2.7.9-3 packages.  


[0]:  http://www.tutorialspoint.com/python/python_multithreading.htm

**Comment by b-harper** [comment]
I am getting the same results with [SCL python27 packages][0].



[0]: https://www.softwarecollections.org/en/scls/rhscl/python27/

**Comment by radar-aol-pl** [comment]
I changed -O2 to -O0 in configure file and rebuilded the package (rpmbuild -ba), but it didn't help.

**Comment by b-harper** [comment]
@radar-aol-pl, I want to say that those configurations are controlled by the $RPM_OPT_FLAGS and %__global_cflags RPM macros.

**Comment by radar-aol-pl** [comment]
Defining these flags in .rpmmacros make the situation even worse:

```
%__global_cflags    -O0 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4
%optflags           -O0 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4
```
All flags are taken from _/usr/lib/rpm/redhat/macros_ and _/usr/lib/rpm/macros_
I just changed -O2 to -O0

```
gdb python2.7 29479
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python2.7...Reading symbols from /usr/lib/debug/usr/bin/python2.7.debug...done.
done.
Attaching to program: /usr/bin/python2.7, process 29479
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Cannot access memory at address 0xa
0x00007f3105b183b3 in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64
```

After installing glibc-debuginfo from http://debuginfo.centos.org/6/x86_64/ I got:

```
gdb python2.7 29479
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python2.7...Reading symbols from /usr/lib/debug/usr/bin/python2.7.debug...done.
done.
Attaching to program: /usr/bin/python2.7, process 29479
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Cannot access memory at address 0xa
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/lib64/ld-2.12.so.debug...done.
done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Cannot access memory at address 0xa
0x00007f3105b183b3 in ?? ()
```

**Comment by b-harper** [comment]
@radar-aol-pl, lets take a step back for a moment.  What is the root problem you are trying to troubleshoot?  I just want to make sure that gdb  is the correct tool for the job.

**Comment by kowalski** [comment]
@b-harper let me answer to the last question (I work with @radar-aol-pl)

We have a python service running on quite o lot of machines. Each process has way more threads that you'd consider reasonable. They make heavy operations, some of them are cpu-, other io-bound. I think you can imagine, that such setup leads to problems. This process often locks itself or refuses to quit for a very long time. This is caused by a considerable number of separate problems which we need to battle one-by-one. 
In order to do this we first need to monitor what's going on. We have a script which detects the process lock down. When it goes down, it extracts for us as much information feasible for debugging as possible. This includes the output of the following command:
```
gdb python PID --batch --eval-command="thread apply all py-bt";
``` 
We find it extremely helpful for battling problems in processes we run under python 2.6 (I'm not joking, we still use 2.6 in some places). Now that we want to migrate to python 2.7 we would like to keep this tool working.

Thank you for you help and please let me know if I can offer any more insist on our case.

**Comment by b-harper** [comment]
@kowalski,

Thanks for that information.  I just wanted to make sure that there was any debug tools in python that might be more appropriate before jumping to gdb.

**Comment by b-harper** [comment]
So I have some additional information that might shed some light on this issue. The stock gdb package is compiled with the --with-python option and against the stock python packages.    The difference between python 2.6 and python 2.7 might be causing this issue.

**Comment by radar-aol-pl** [comment]
Thanks for the hint @b-harper . I'll give it a shot to rebuild gdb with python2.7.

**Comment by b-harper** [comment]
@radar-aol-pl and @kowalski, were yall able to get determine the root cause of your issue?

**Comment by radar-aol-pl** [comment]
Not yet. And since we use even three versions of python (2.6, 2.7 and 3.4) side by side on some of our machines, it's tricky to make proper gdb for them.

**Comment by b-harper** [comment]
@radar-aol-pl, I wanted to check in and see if yall were able to resolve this issue.

**Comment by radar-aol-pl** [comment]
@b-harper No, we abandoned gdb.
